// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const AUTH_ERROR = "AUTH_ERROR";
export const REMBER_LOCATION_PUNCH_CLOCK = "REMBER_LOCATION_PUNCH_CLOCK";
export const REMEMBER_COMPANY_PUNCH_CLOCK = "REMEMBER_COMPANY_PUNCH_CLOCK";
export const CURRENT_PROFILE = "CURRENT_PROFILE";

//Sticky
export const GET_STICKY = "GET_STICKY";
export const NOTES_UPDATE = "NOTES_UPDATE";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const UPDATE_ALL_NOTES_SUCCESS = "UPDATE_ALL_NOTES_SUCCESS";

//Contact
export const GET_All_CONTACT_SUCCESS = "GET_All_CONTACT_SUCCESS";
export const ON_ADD_CONTACT_SUCCESS = "ON_ADD_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

// Company
export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const COMPANY_ERROR = "COMPANY_ERROR";

// Common
export const COMMON_GET_COMPANY_REQUEST = "COMMON_GET_COMPANY_REQUEST";
export const COMMON_GET_COMPANY_SUCCESS = "COMMON_GET_COMPANY_SUCCESS";
export const SET_ACTIVE_COMPANY = "SET_ACTIVE_COMPANY";
export const UPDATE_CONTRACTOR_VERIFY_DETAIL =
  "UPDATE_CONTRACTOR_VERIFY_DETAIL";
export const UPDATE_EMPLOYEE_VERIFY_DETAIL = "UPDATE_EMPLOYEE_VERIFY_DETAIL";

// People

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const ADD_CONTRACTOR_REQUEST = "ADD_CONTRACTOR_REQUEST";
export const UPDATE_CONTRACTOR_REQUEST = "UPDATE_CONTRACTOR_REQUEST";
export const GET_PEOPLE_REQUEST = "GET_PEOPLE_REQUEST";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const PEOPLE_ERROR = "PEOPLE_ERROR";
export const GET_VALID_PIN = "GET_VALID_PIN";
export const GET_VALID_PIN_SUCCESS = "GET_VALID_PIN_SUCCESS";
export const GET_VALID_PIN_ERROR = "GET_VALID_PIN_ERROR";
export const NEW_ADDED_EMPLOYEE_EMAIL = "NEW_ADDED_EMPLOYEE_EMAIL";
export const GET_NEW_ADDED_EMPLOYEE_EMAIL = "GET_NEW_ADDED_EMPLOYEE_EMAIL";

// Jobs

export const CREATE_JOB = "CREATE_JOB";
export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

// Department

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
